### ISSUE TITLE
[BUG] Game cashing when using option 'Save and Quit'

### ISSUE THREAD

**Issue by Kyrela** [fortwoone/Oracle-Project#11]
### Describe the bug
The game is crashing after choosing option 'Save and Quit' (Sauv. et Quitter) from the inventory menu.

### To Reproduce
1. Load a save file
2. Press `Enter`, then `Space` until the 'Save' option appears
3. Press `Y` to validate, then choose the option 'Save quand Quit'
4. Press `Y` to validate

### Expected behavior
The game closes without errors.

### Actual behavior
The game closes with an error.

### Screenshots
![animated gif of the error](https://hosting.webspell.fr/images/2021/11/20/8215511685bd944c0967959df51d5784.gif)

### System informations
 - OS: Windows 10
 - Version or commit: 8dbcfe692243836459a435cc7f18f2e6c1c62d59

### Additional context
Traceback of the error:
```py
Traceback (most recent call last):
  File "Oracle-Project\testEngine.py", line 2028, in <module>
    im.reMove()
  File "Oracle-Project\src\gui.py", line 2112, in reMove
    post_event(CONTINUE_STREAM)
  File "Oracle-Project\src\utils.py", line 1104, in post_event
    pygame.event.post(evt_obj(**attrs))
pygame.error: video system not initialized
```

**Comment by fortwoone** [comment]
This is the intended behaviour until the title screen is implemented for good

**Comment by Kyrela** [comment]
but it should be possible to add a simple `exit()` in the meantime, no?
